### ISSUE TITLE
可以加一个浏览器的插件

### ISSUE THREAD

**Issue by yan5xu** [vito-go/mywords#1]
参考relingo
🙋我可以贡献点力量

**Comment by vito-go** [comment]
感谢您的建议。目前暂无制作浏览器插件的计划。
目前文章的单词解析、数据存储、单词查询等功能需要有适宜的应用环境来承载实现，web版本/插件无法集成这些功能。
目前支持Android、Linux和Windows平台，并具备数据同步特性，以方便用户在不同设备间学习。
我们会记录您的需求，并在未来的开发中予以考虑。感谢您的理解和支持。

**Comment by vito-go** [comment]
> 数据同步能支持webdav吗？

因为目前已经有数据同步的方案（包括通过域名/IP同步，支持本地文件备份、文件分享），暂时无支持webdav的计划。
但是我会持续关注用户需求和反馈，如果有足够的用户需求，会考虑添加webdav支持。
