### ISSUE TITLE
【功能需求】将web部署linux的数据和配置文件，放在运行文件所在文件夹，避免免费的云服务器无法取得mkdir权限

### ISSUE THREAD

**Issue by aiyou9** [vito-go/mywords#17]
.pid文件，自行设置，有的免费服务器不给写入
![image](https://github.com/vito-go/mywords/assets/15712822/316f6e82-de3c-4732-a566-aa7a1421b589)

**Comment by vito-go** [comment]
You can use "rootDir" command line param to specify the program data directory.
```shell
./mywords-web-linux -h
```
output:
 ```
Usage of ./mywords-web-linux:
  -dictPort int
    	dict port (default 18961)
  -port int
    	http server port (default 18960)
  -rootDir string
    	root dir (default "/home/vito/.local/share/com.example.mywords")
```
For example: 
```shell
./mywords-web-linux  -rootDir ./mywords-data
```
If  the "rootDir" directory does not exist, it will be created.
The "rootDir" will store not only the ".pid" file, but also all the program data, for example, articles, dicts, and leaning records and so on.

**Comment by aiyou9** [comment]
great  it work

my test site https://aiyou9.alwaysdata.net/  run  in a free cloud with  100mb space

**Comment by aiyou9** [comment]
great it work

my test site can run in a free cloud with 100mb space
