### ISSUE TITLE
known_words.json

### ISSUE THREAD

**Issue by hodge1995** [vito-go/mywords#20]
known_words.json 能提供一下吗？

**Comment by vito-go** [comment]
known_words.json这个文件由用户自己生成的，存储的用户自己学习的单词。
格式为map[string]map[string]int, 
例如
```
"y": {
    "year": 3,
    "you": 1,
    "your": 3,
    "youth": 3
  }
```
key为单词首字母,例如k,
value是一个map结构，key为单词，如`year`, value 为3,代表熟悉程度。

**Comment by hodge1995** [comment]
谢谢解答，如果一个新用户单词表是空白的，那么又怎么标记单词的难易级别？

**Comment by vito-go** [comment]
对于新用户，除了系统自动踢出一些虚词(如,in, on, at等)默认所有的单词都是陌生(level为0)。用户在阅读文章的时候，可以手动对单词进行标记。随着时间的积累，用户的单词表会越来越多，陌生的单词会越来越少。
